# Generated by Django 2.2.5 on 2021-01-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210106_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='cuntry',
            new_name='country',
        ),
    ]
