# Generated by Django 2.2.5 on 2021-01-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(),
        ),
    ]
